#!/bin/bash

GENLIB=~/scripts/gen_libraries
VERSION=`cat ~/.dropbox-dist/VERSION`

. $GENLIB

LIBS=`compile_list ~/.dropbox-dist/dropbox-lnx.x86_64-${VERSION}/ python2.7`

firejail --private-lib="$LIBS" dropbox start
